CC = gcc

SRC = $(wildcard *.c)

compiler:
	$(CC) $(CFLAGS) -o main $(SRC)

t1:
	./main grammar.txt t1.txt

t2:
	./main grammar.txt t2.txt

t3:
	./main grammar.txt t3.txt

t4:
	./main grammar.txt t4.txt

t5:
	./main grammar.txt t5.txt

t6:
	./main grammar.txt t6.txt