CC = gcc

SRC = $(wildcard *.c)

compiler:
	$(CC) $(CFLAGS) -o main $(SRC)

t1:
	./main grammar.txt testcases/t1.txt

t2:
	./main grammar.txt testcases/t2.txt

t3:
	./main grammar.txt testcases/t3.txt

t4:
	./main grammar.txt testcases/t4.txt

t5:
	./main grammar.txt testcases/t5.txt

t6:
	./main grammar.txt testcases/t6.txt
